language: emacs
env:
  matrix:
    - "CHECK_TARGET=check LISP=sbcl EMACS=emacs23"
    - "CHECK_TARGET=check LISP=sbcl EMACS=emacs24"
    - "CHECK_TARGET=check LISP=cmucl EMACS=emacs23"
    - "CHECK_TARGET=check LISP=cmucl EMACS=emacs24"
    - "CHECK_TARGET=check-fancy LISP=sbcl EMACS=emacs23"
    - "CHECK_TARGET=check-fancy LISP=sbcl EMACS=emacs24"
    - "CHECK_TARGET=check-fancy LISP=cmucl EMACS=emacs23"
    - "CHECK_TARGET=check-fancy LISP=cmucl EMACS=emacs24"
  global:
#    - SOME_TOKEN=some_value

install:
  - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs23-nox;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24-nox;
    fi
script:
  - LISP_BIN=$LISP EMACS_BIN=$EMACS make $CHECK_TARGET
